// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
import type { Dimension, ExperimentalDimension, Severity, Stability } from '../types.js';

export interface RuleMetadata {
  id: string;
  title: string;
  dimension: Dimension | ExperimentalDimension;
  severity: Severity;
  summary: string;
  detection: string;
  remediation: string;
  catesSection: string;
  autofix?: boolean;
  /** Defaults to 'stable'. Experimental rules are non-normative and SemVer-exempt. */
  stability?: Stability;
}

export const RULE_CATALOG: RuleMetadata[] = [
  { id: 'TE001', title: 'Excessive Always-Loaded Token Count', dimension: 'token-efficiency', severity: 'medium', summary: 'Always-loaded configuration exceeds 1,500 tokens.', detection: 'Sum active always-loaded config tokens and flag totals above 1,500.', remediation: 'Move context-specific guidance to conditional agent files or on-demand prompt files.', catesSection: '9.2', autofix: false },
  { id: 'TE002', title: 'Excessive Inline Code Examples', dimension: 'token-efficiency', severity: 'medium', summary: 'Inline code block exceeds 200 tokens.', detection: 'Find fenced code blocks over 200 cl100k_base tokens.', remediation: 'Move examples to referenced files or prompt-library entries.', catesSection: '9.2', autofix: false },
  { id: 'TE003', title: 'Generic Filler Instructions', dimension: 'token-efficiency', severity: 'low', summary: 'Instruction restates model-default behavior or vague best-practice language.', detection: 'Match known generic filler phrases.', remediation: 'Remove filler or replace with project-specific instructions.', catesSection: '9.2', autofix: false },
  { id: 'TE004', title: 'Forced Verbosity', dimension: 'token-efficiency', severity: 'high', summary: 'Instructions require verbose output for every response.', detection: 'Match unconditional verbosity patterns.', remediation: 'Make verbosity conditional by task complexity.', catesSection: '9.2', autofix: false },
  { id: 'TE005', title: 'Negative Constraint Spam', dimension: 'token-efficiency', severity: 'medium', summary: 'More than 60% of bullet instructions are negative constraints.', detection: 'Compare negative bullet count to total bullet count.', remediation: 'Rewrite as positive preferred behaviors.', catesSection: '9.2', autofix: false },
  { id: 'TE006', title: 'Cross-File Duplication', dimension: 'token-efficiency', severity: 'high', summary: 'Near-duplicate blocks appear across multiple config files.', detection: 'Compare normalized multi-line paragraphs across files.', remediation: 'Keep shared guidance in one precedence-appropriate location.', catesSection: '9.2', autofix: false },
  { id: 'TE007', title: 'Within-File Duplicate Instructions', dimension: 'token-efficiency', severity: 'medium', summary: 'Same normalized instruction appears more than once in one file.', detection: 'Find repeated normalized lines or paragraphs.', remediation: 'Remove duplicated instructions.', catesSection: '9.2', autofix: true },
  { id: 'TE008', title: 'Unbounded Context Includes', dimension: 'token-efficiency', severity: 'medium', summary: 'Instruction file pulls in context via recursive globs, whole-directory references, or many @file includes.', detection: 'Scan instruction files for @include directives using ** globs, trailing-slash directories, or high include fan-out.', remediation: 'Reference only the specific files needed, or move bulk content to on-demand prompt files.', catesSection: '9.2', autofix: false },

  { id: 'SEC001', title: 'Hardcoded Secrets', dimension: 'security', severity: 'critical', summary: 'Credential-like value appears in configuration.', detection: 'Match known API key, token, password, private key, and connection string patterns.', remediation: 'Remove immediately and use environment variables or secret managers.', catesSection: '9.3', autofix: false },
  { id: 'SEC002', title: 'Injection Vectors', dimension: 'security', severity: 'high', summary: 'Untrusted/dynamic values are templated into instruction text, or a prompt-injection payload is present.', detection: 'Match untrusted-source interpolation (user/input/args/query) and injection payload phrases; ignore benign code interpolation and env references.', remediation: 'Pass dynamic values through structured, validated tool inputs instead of instruction prose.', catesSection: '9.3', autofix: false },
  { id: 'SEC003', title: 'Overly Permissive Scope', dimension: 'security', severity: 'high', summary: 'Instructions grant broad file, command, or tool access.', detection: 'Match unrestricted action/file/tool patterns.', remediation: 'Define explicit scoped permissions.', catesSection: '9.3', autofix: false },
  { id: 'SEC004', title: 'Missing Prompt Protection', dimension: 'security', severity: 'medium', summary: 'Instruction-bearing config lacks anti-extraction directive.', detection: 'Flag files over 200 chars without reveal/share/disclose protection language.', remediation: 'Add a prompt-protection directive.', catesSection: '9.3', autofix: true },
  { id: 'SEC005', title: 'System Prompt Leakage Risk', dimension: 'security', severity: 'high', summary: 'Instructions create a path for disclosing system instructions.', detection: 'Match conditional or explicit instruction disclosure language.', remediation: 'Remove disclosure paths and make protection unconditional.', catesSection: '9.3', autofix: false },
  { id: 'SEC006', title: 'Unsafe Execution Patterns', dimension: 'security', severity: 'high', summary: 'Config includes unsafe commands or verification bypasses.', detection: 'Match curl-pipe-shell, eval, destructive filesystem, chmod 777, no-verify, or disabled TLS patterns.', remediation: 'Remove unsafe patterns or label them as prohibited with safe alternatives.', catesSection: '9.3', autofix: false },
  { id: 'SEC007', title: 'Autonomy / Approval Bypass', dimension: 'security', severity: 'critical', summary: 'Configuration removes the human-approval or tool-permission checkpoint.', detection: 'Match permission-bypass flags/modes (e.g. --dangerously-skip-permissions, bypassPermissions, auto-approve, allow-all-tools) and "without approval" phrasing.', remediation: 'Keep approval prompts on; scope auto-approval to a small set of explicitly-listed safe tools.', catesSection: '9.3', autofix: false },

  { id: 'SPC001', title: 'Vague Language', dimension: 'specificity', severity: 'medium', summary: 'Instruction uses subjective or undefined language.', detection: 'Match vague phrases such as best practices, appropriate, robust, or common sense.', remediation: 'Replace with concrete criteria and examples.', catesSection: '9.4', autofix: false },
  { id: 'SPC002', title: 'Missing Project Context', dimension: 'specificity', severity: 'medium', summary: 'Large config lacks concrete project references.', detection: 'Flag files over 500 tokens with no file paths, directories, or technology/config references.', remediation: 'Reference real directories, config files, and stack details.', catesSection: '9.4', autofix: false },
  { id: 'SPC003', title: 'Missing Architecture Structure', dimension: 'specificity', severity: 'low', summary: 'Config lacks architecture or module structure guidance.', detection: 'Flag files over 300 tokens with no architecture/module/service references.', remediation: 'Add a short project layout section.', catesSection: '9.4', autofix: false },
  { id: 'SPC004', title: 'Long Abstract Instruction Block', dimension: 'specificity', severity: 'low', summary: 'Long bullet block lacks concrete anchors.', detection: 'Find eight or more consecutive abstract bullets.', remediation: 'Add examples, file references, or decision criteria.', catesSection: '9.4', autofix: false },

  { id: 'CMP001', title: 'No Configuration Content', dimension: 'completeness', severity: 'high', summary: 'No coding-agent configuration was found.', detection: 'No active config content after discovery.', remediation: 'Create root instructions with stack, conventions, testing, and scope.', catesSection: '9.5', autofix: false },
  { id: 'CMP002', title: 'Missing Essential Topics', dimension: 'completeness', severity: 'medium', summary: 'Configuration omits key topics like tests, errors, style, architecture, security, scope, or output.', detection: 'Search combined config for essential topic coverage.', remediation: 'Add concise sections for missing topics.', catesSection: '9.5', autofix: false },
  { id: 'CMP003', title: 'Monolithic Configuration File', dimension: 'completeness', severity: 'low', summary: 'Only one config file exists and it exceeds 200 lines.', detection: 'Count config files and line count.', remediation: 'Split universal guidance from scoped or on-demand guidance.', catesSection: '9.5', autofix: false },

  { id: 'CNF001', title: 'Contradictory Instructions', dimension: 'conflict-reachability', severity: 'high', summary: 'Loaded instructions conflict.', detection: 'Match known contradictory instruction pairs.', remediation: 'Resolve contradiction or scope conflicting guidance conditionally.', catesSection: '9.6', autofix: false },
  { id: 'CNF002', title: 'Missing Harness Element', dimension: 'harness-quality', severity: 'medium', summary: 'Configuration lacks important agent guardrails.', detection: 'Check for scope limits, failure handling, output constraints, prohibited actions, and verification.', remediation: 'Add concise guardrails for missing harness elements.', catesSection: '9.6', autofix: false },

  { id: 'PRM001', title: 'Missing Prompt Purpose Header', dimension: 'specificity', severity: 'low', summary: 'Prompt lacks clear purpose/trigger metadata.', detection: 'Flag prompt files over 50 tokens without heading or purpose markers.', remediation: 'Add frontmatter or a purpose heading.', catesSection: 'Annex B', autofix: true },
  { id: 'PRM002', title: 'Oversized Prompt File', dimension: 'token-efficiency', severity: 'medium', summary: 'Prompt exceeds 1,000 tokens.', detection: 'Token-count prompt files.', remediation: 'Split into smaller prompts or referenced files.', catesSection: 'Annex B', autofix: false },
  { id: 'PRM003', title: 'Excessive Hardcoded File Paths', dimension: 'specificity', severity: 'low', summary: 'Prompt references more than five concrete source paths.', detection: 'Count source path references.', remediation: 'Use directory references or placeholders.', catesSection: 'Annex B', autofix: false },
  { id: 'PRM004', title: 'No Variables in Large Prompt', dimension: 'completeness', severity: 'low', summary: 'Large prompt lacks placeholders.', detection: 'Flag prompts over 200 tokens without variable markers.', remediation: 'Add placeholders for reusable inputs.', catesSection: 'Annex B', autofix: false },
  { id: 'PRM005', title: 'Prompt Library Sprawl', dimension: 'completeness', severity: 'low', summary: 'Prompt library has more than 15 prompts.', detection: 'Count prompt files.', remediation: 'Add index, grouping, or merge overlapping prompts.', catesSection: 'Annex B', autofix: false },

  { id: 'MCP001', title: 'Invalid MCP Config Syntax', dimension: 'completeness', severity: 'medium', summary: 'MCP config cannot be parsed.', detection: 'Parse MCP JSON/YAML.', remediation: 'Fix syntax and validate before commit.', catesSection: 'Annex C', autofix: false },
  { id: 'MCP002', title: 'Secrets in MCP Configuration', dimension: 'security', severity: 'critical', summary: 'MCP config contains hardcoded credentials.', detection: 'Match secret patterns in parsed MCP config.', remediation: 'Use env vars or secret-manager bindings.', catesSection: 'Annex C', autofix: false },
  { id: 'MCP003', title: 'Insecure MCP Endpoint', dimension: 'security', severity: 'high', summary: 'MCP config references non-localhost HTTP.', detection: 'Find http:// endpoints outside localhost.', remediation: 'Use HTTPS for remote endpoints.', catesSection: 'Annex C', autofix: false },
  { id: 'MCP004', title: 'Missing MCP Server Descriptions', dimension: 'specificity', severity: 'low', summary: 'MCP servers/tools lack descriptions.', detection: 'Check server/tool objects for description fields.', remediation: 'Add when-to-use descriptions.', catesSection: 'Annex C', autofix: false },
  { id: 'MCP005', title: 'Shell Operators in MCP Command', dimension: 'security', severity: 'high', summary: 'MCP stdio command contains shell operators.', detection: 'Match shell operators in command strings.', remediation: 'Use command plus args array or reviewed wrapper script.', catesSection: 'Annex C', autofix: false },
  { id: 'MCP006', title: 'Unpinned MCP Server Package', dimension: 'security', severity: 'medium', summary: 'MCP server runs a package via npx/uvx/dlx with no version pin.', detection: 'Inspect stdio server command/args for npx/uvx/dlx invocations lacking an exact version or commit pin.', remediation: 'Pin to an exact version or vetted commit and review updates before bumping.', catesSection: 'Annex C', autofix: false },

  { id: 'STP001', title: 'Pipe-to-Shell Setup Pattern', dimension: 'security', severity: 'high', summary: 'Setup steps pipe curl to shell.', detection: 'Match curl piped to sh/bash.', remediation: 'Pin versions and verify downloads.', catesSection: 'Annex D', autofix: false },
  { id: 'STP002', title: 'Missing Dependency Caching', dimension: 'token-efficiency', severity: 'low', summary: 'Setup installs dependencies without caching.', detection: 'Install step exists without cache indicators.', remediation: 'Add package-manager cache restore/save.', catesSection: 'Annex D', autofix: false },
  { id: 'STP003', title: 'Broad Setup Permissions', dimension: 'security', severity: 'medium', summary: 'Setup grants broad permissions.', detection: 'Find broad write permissions beyond normal content changes.', remediation: 'Reduce permissions to least privilege.', catesSection: 'Annex D', autofix: false },
  { id: 'STP004', title: 'Missing Test Framework Setup', dimension: 'completeness', severity: 'medium', summary: 'Setup lacks test runner or test command.', detection: 'Search setup for test runner patterns.', remediation: 'Ensure agent can run tests.', catesSection: 'Annex D', autofix: false },
  { id: 'STP005', title: 'Missing Linter Setup', dimension: 'completeness', severity: 'low', summary: 'Setup lacks lint/static-analysis command.', detection: 'Search setup for lint/format/static-check patterns.', remediation: 'Expose lint/static-analysis command.', catesSection: 'Annex D', autofix: false },

  { id: 'HK001', title: 'Interactive Hook', dimension: 'conflict-reachability', severity: 'medium', summary: 'Hook may block automated agent workflows.', detection: 'Match interactive/prompt/confirm patterns.', remediation: 'Make hooks non-interactive.', catesSection: 'Annex E', autofix: false },
  { id: 'HK002', title: 'Heavy Hook Operation', dimension: 'token-efficiency', severity: 'low', summary: 'Hook includes heavyweight work.', detection: 'Match container/build-image patterns.', remediation: 'Move heavyweight checks to CI.', catesSection: 'Annex E', autofix: false },
  { id: 'HK003', title: 'Outdated Hook Version', dimension: 'security', severity: 'low', summary: 'Hook is pinned to very old major version.', detection: 'Flag v0.x/v1.x hook revisions.', remediation: 'Update to current stable versions.', catesSection: 'Annex E', autofix: false },
  { id: 'EDC001', title: 'Invalid Editor Settings Syntax', dimension: 'completeness', severity: 'low', summary: 'Editor config with AI settings cannot be parsed.', detection: 'Parse relevant settings file.', remediation: 'Fix JSON/JSONC/YAML syntax.', catesSection: 'Annex F', autofix: false },
  { id: 'EDC002', title: 'AI Assistance Disabled Broadly', dimension: 'completeness', severity: 'low', summary: 'AI assistance disabled for many contexts.', detection: 'Count disabled language/context settings.', remediation: 'Confirm disabled contexts are intentional.', catesSection: 'Annex F', autofix: false },
  { id: 'EDC003', title: 'Overly Permissive Tool Allowlist', dimension: 'security', severity: 'high', summary: 'Settings allowlist grants unconstrained shell, write, or all-tools access.', detection: 'Parse permissions.allow for bare/wildcard execution or write tools and a global "*".', remediation: 'Constrain each allowed tool to specific safe invocations; never allow a bare "*".', catesSection: 'Annex F', autofix: false },

  { id: 'AGT001', title: 'Subagent Missing Tool Restriction', dimension: 'security', severity: 'high', summary: 'Subagent declares no tool scope and inherits the full toolset.', detection: 'Flag agent-definition files whose frontmatter has no tools/allowed-tools key.', remediation: 'Declare an explicit tools list granting only what the subagent needs.', catesSection: '9.8', autofix: false },
  { id: 'AGT002', title: 'Subagent Missing Description', dimension: 'specificity', severity: 'low', summary: 'Subagent lacks a description/trigger for routing.', detection: 'Flag agent-definition files with no description/name/purpose metadata or heading.', remediation: 'Add a description (and name) stating when the subagent should be invoked.', catesSection: '9.8', autofix: false },

  { id: 'CMD001', title: 'Command Auto-Executes Shell', dimension: 'security', severity: 'high', summary: 'Slash command runs shell on invocation via bang-syntax or a Bash tool grant.', detection: 'Flag command files with !-prefixed execution directives or allowed-tools granting Bash.', remediation: 'Remove side-effect shell execution or constrain it to a fixed, non-parameterized command.', catesSection: '9.8', autofix: false },

  // ─── Experimental (non-normative) cache/output-shaping rules ─────────────────
  // These carry ZERO scoring weight, are excluded from conformance + CI gates,
  // and are SemVer-exempt. See docs/EXPERIMENTAL-CACHE-OUTPUT-DIMENSIONS.md.
  { id: 'CS001', title: 'Volatile Tokens in Always-Loaded Config', dimension: 'cache-shaping', severity: 'high', summary: 'Always-loaded config embeds volatile values (dates, UUIDs, build numbers, git SHAs) that bust the cacheable prefix every call.', detection: 'Scan always-loaded files for timestamp/date/UUID/build/SHA patterns or "current date/time" directives.', remediation: 'Move volatile values out of the always-loaded prefix; inject them via tool inputs at the end of context instead.', catesSection: '9.9', autofix: false, stability: 'experimental' },
  { id: 'CS002', title: 'Dynamic-Before-Static Ordering', dimension: 'cache-shaping', severity: 'medium', summary: 'Variable placeholders or includes appear ahead of a large static block, shrinking the cacheable prefix.', detection: 'Detect ${…}/{{…}}/@include placeholders positioned before the bulk of static content.', remediation: 'Put stable, static content first; place variable/dynamic content at the end.', catesSection: '9.9', autofix: false, stability: 'experimental' },
  { id: 'CS003', title: 'Non-Deterministic Context Directive', dimension: 'cache-shaping', severity: 'medium', summary: 'Instructions inject live/volatile state at the top (current git status, latest logs, today\'s date).', detection: 'Match directives that pull live/volatile state into the preamble.', remediation: 'Fetch volatile state on-demand via tools rather than embedding it in always-loaded instructions.', catesSection: '9.9', autofix: false, stability: 'experimental' },
  { id: 'CS004', title: 'Unstable Tool/Context Ordering', dimension: 'cache-shaping', severity: 'low', summary: 'Directives randomize or re-sort tool lists / retrieved context per call.', detection: 'Match shuffle/randomize/re-sort directives over tools or context.', remediation: 'Keep tool and context ordering stable and deterministic across calls.', catesSection: '9.9', autofix: false, stability: 'experimental' },
  { id: 'CS005', title: 'Fragmented Preamble (No Shared Prelude)', dimension: 'cache-shaping', severity: 'info', summary: 'High cross-file near-duplication of preamble that could be one shared cacheable prelude.', detection: 'Correlate with TE006 cross-file duplication of leading preamble blocks.', remediation: 'Hoist the shared preamble into a single, stable, precedence-appropriate prelude.', catesSection: '9.9', autofix: false, stability: 'experimental' },

  { id: 'OS001', title: 'Missing Output Contract', dimension: 'output-shaping', severity: 'medium', summary: 'Config never bounds output (no length cap, no code-only/no-preamble, no format spec).', detection: 'Flag instruction-bearing configs that set no output bound or format contract.', remediation: 'Add a concise output contract (length cap, "code only, no preamble", or required format).', catesSection: '9.10', autofix: false, stability: 'experimental' },
  { id: 'OS002', title: 'Full-File Rewrite Mandate', dimension: 'output-shaping', severity: 'high', summary: 'Instructions require emitting entire files instead of diffs/patches — large, avoidable output.', detection: 'Match "return/output the complete/entire file" style mandates.', remediation: 'Prefer diffs/patches or targeted edits; reserve full-file output for new files.', catesSection: '9.10', autofix: false, stability: 'experimental' },
  { id: 'OS003', title: 'Unconditional Verbose Reasoning', dimension: 'output-shaping', severity: 'medium', summary: 'Forces detailed chain-of-thought/explanation on every response regardless of task.', detection: 'Match unconditional "explain your reasoning / think step by step on every response" directives.', remediation: 'Make reasoning depth conditional on task complexity rather than global.', catesSection: '9.10', autofix: false, stability: 'experimental' },
  { id: 'OS004', title: 'Output Echo / Restatement', dimension: 'output-shaping', severity: 'low', summary: 'Instructs the agent to restate the prompt, echo inputs, or repeat context back.', detection: 'Match restate/echo/repeat-back directives.', remediation: 'Remove echo/restatement requirements; have the agent act directly.', catesSection: '9.10', autofix: false, stability: 'experimental' },
  { id: 'OS005', title: 'Verbose Format Mandate', dimension: 'output-shaping', severity: 'info', summary: 'Requires heavyweight formatting (decorative sections, full tables) where compact output suffices.', detection: 'Match mandates for heavyweight/decorative formatting on every response.', remediation: 'Default to compact output; reserve rich formatting for when it is requested.', catesSection: '9.10', autofix: false, stability: 'experimental' },
];

export function getRule(id: string): RuleMetadata | undefined {
  return RULE_CATALOG.find(rule => rule.id === id);
}

/** Stable rules only — the normative catalog used for scoring/conformance. */
export function stableRules(): RuleMetadata[] {
  return RULE_CATALOG.filter(rule => rule.stability !== 'experimental');
}

/** Experimental, non-normative rules (cache/output shaping). */
export function experimentalRules(): RuleMetadata[] {
  return RULE_CATALOG.filter(rule => rule.stability === 'experimental');
}

export function rulesAsJson(): string {
  return JSON.stringify(RULE_CATALOG, null, 2);
}
