{{- if and .Values.reports.persistence.enabled (not .Values.reports.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cates.fullname" . }}-reports
  labels:
    {{- include "cates.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.reports.persistence.accessMode }}
  {{- with .Values.reports.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.reports.persistence.size | quote }}
{{- end }}
