{{- if and .Values.githubToken.value (not .Values.githubToken.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cates.fullname" . }}-gh
  labels:
    {{- include "cates.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.githubToken.value | quote }}
{{- end }}
