{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cates.serviceAccountName" . }}
  labels:
    {{- include "cates.labels" . | nindent 4 }}
    {{- if .Values.githubToken.workloadIdentity.enabled }}
    azure.workload.identity/use: "true"
    {{- end }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.githubToken.workloadIdentity.enabled }}
    azure.workload.identity/client-id: {{ .Values.githubToken.workloadIdentity.clientId | quote }}
    {{- if .Values.githubToken.workloadIdentity.tenantId }}
    azure.workload.identity/tenant-id: {{ .Values.githubToken.workloadIdentity.tenantId | quote }}
    {{- end }}
    {{- end }}
{{- end -}}
